POST https://medieinstitutet-wie-products.azurewebsites.net/api/orders
Content-Type: application/json


    {

        "paymentMethod": "Paypal",

        "createdBy": "Batmans kompis",

             "orderRows":   [
    {
        "product": "null",
        "productId": 76,
        "price": 199,
        "amount": 1,
    }
]
    }


###

GET https://medieinstitutet-wie-products.azurewebsites.net/api/orders
Content-Type: application/json