POST https://medieinstitutet-wie-products.azurewebsites.net/api/orders
Content-Type: application/json


{
  "createdBy": "NARJA",
  "paymentMethod": "Paypal",
  "totalPrice": 199,
  "orderRows": [
    {
      "productId": 76,
      "product": null,
      "price": 199,
      "amount": 1
    }
  ]
}


###

GET https://medieinstitutet-wie-products.azurewebsites.net/api/orders
Content-Type: application/json